Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: false
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: ./list/fine_val.txt
  split: val  # split in [train, val and test]
  base_size: 1024  # based size for scaling
  test_h: 449
  test_w: 449
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: ./Models/Adversarial_version02_onlyAdversarialImages_cosineInner_step3_e0.03_SGD_pretrainedNormalResnet_PSNET_AUX_batch16__270.pt # evaluation model path
  save_folder: ./results/  # results save folder
  colors_path: ./config/cityscapes_colors.txt  # path of dataset colors
  names_path: ./config/cityscapes_names.txt  # path of dataset category namesDATA:
  data_root: ../../../CitySpace/Data/ok/
  train_list: ./list/fine_train.txt
  val_list: ./list/fine_val.txt
  classes: 19

  mode: "my"
  attack: ""
  workers: 0
  zoom_factor: 8
  layers: 50